<a href="https://colab.research.google.com/github/Kggzzz/data_viz/blob/main/Quiz03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
path = '/content/drive/My Drive/Data_viz'
os.listdir(path)

['covid-19-daily_data_dictionary.xlsx',
 'pm-18-jan-2021.csv',
 '18-jan-2021.xlsx',
 'pm-24-jan-2021.csv',
 'Project1-StuList-1-63-ตัดเกรด_renamed.xlsx',
 'คะแนนอาจารย์ที่ปรึกษา_renamed.xlsx',
 'คะแนนสอบปากเปล่าของกรรมการสอบ_renamed.xlsx',
 '3.-41-58.csv',
 '3.-41-58.xls',
 '-.57-.58-1.xls']

In [5]:
_file_path = os.path.join(path,'-.57-.58-1.xls')
print(sale_file_path)

/content/drive/My Drive/Data_viz/-.57-.58-1.xls

In [6]:
sale_df= pd.read_excel(sale_file_path,sheet_name=0,skiprows=0,header=4)
sale_df

   ลำดับ  ... เหตุผลที่คัดเลือกโดยสรุป
0    ที่  ...                      NaN
1      1  ...           เป็นผู้รับจ้าง
2      2  ...           เป็นผู้รับจ้าง
3      3  ...           เป็นผู้รับจ้าง
4      4  ...           เป็นผู้รับจ้าง
..   ...  ...                      ...
95    56  ...           เป็นผู้รับจ้าง
96    57  ...           เป็นผู้รับจ้าง
97    58  ...           เป็นผู้รับจ้าง
98    59  ...           เป็นผู้รับจ้าง
99    60  ...           เป็นผู้รับจ้าง

[100 rows x 9 columns]

In [8]:
sale = pd.read_excel(sale_file_path,sheet_name=1,skiprows=0,header=4)
sale

                                                ลำดับ  ...  เหตุผลที่คัดเลือกโดยสรุป
0                                                 ที่  ...                       NaN
1                                                   1  ...            เป็นผู้รับจ้าง
2                                                   2  ...            เป็นผู้รับจ้าง
3                                                   3  ...            เป็นผู้รับจ้าง
4                                                   4  ...            เป็นผู้รับจ้าง
5                                                   5  ...            เป็นผู้รับจ้าง
6                                                   6  ...            เป็นผู้รับจ้าง
7                                                   7  ...            เป็นผู้รับจ้าง
8                                                   8  ...            เป็นผู้รับจ้าง
9                                                   9  ...            เป็นผู้รับจ้าง
10                                                 10  ...            เป็นผู้รับจ้าง
11                                                 11  ...            เป็นผู้รับจ้าง
12                                                 12  ...            เป็นผู้รับจ้าง
13                                                 13  ...            เป็นผู้รับจ้าง
14                                                 14  ...            เป็นผู้รับจ้าง
15                                                 15  ...            เป็นผู้รับจ้าง
16                                                NaN  ...                แบบ สขร. 1
17  สรุปผลการดำเนินการจัดซื้อในรอบเดือน พฤษจิกายน ...  ...                       NaN
18         สำนักงานปลัดกระทรวงวิทยาศาสตร์และเทคโนโลยี  ...                       NaN
19                                                NaN  ...                       NaN
20                                              ลำดับ  ...  เหตุผลที่คัดเลือกโดยสรุป
21                                                ที่  ...                       NaN
22                                                 16  ...            เป็นผู้รับจ้าง
23                                                 17  ...            เป็นผู้รับจ้าง
24                                                 18  ...            เป็นผู้รับจ้าง
25                                                 19  ...            เป็นผู้รับจ้าง
26                                                 20  ...            เป็นผู้รับจ้าง
27                                                 21  ...            เป็นผู้รับจ้าง
28                                                 22  ...            เป็นผู้รับจ้าง
29                                                 23  ...            เป็นผู้รับจ้าง
30                                                 24  ...            เป็นผู้รับจ้าง
31                                                 25  ...            เป็นผู้รับจ้าง
32                                                 26  ...            เป็นผู้รับจ้าง
33                                                 27  ...            เป็นผู้รับจ้าง
34                                                 28  ...            เป็นผู้รับจ้าง
35                                                 29  ...            เป็นผู้รับจ้าง
36                                                 30  ...            เป็นผู้รับจ้าง

[37 rows x 9 columns]

In [ ]:
oct57 = pd.read_excel('จัดซื้อ 57-58.xls', sheet_name=0,header=4, skipfooter=20) #utf-8 -- latin1
oct57 = oct57.dropna()
oct57

In [ ]:
oct57 = oct57.rename(columns={'Unnamed: 5' : 'ราคาเสนอ', 'Unnamed: 7': 'ราคาซื้อ'})
oct57

In [ ]:
nov57 = pd.read_excel('จัดซื้อ 57-58.xls', sheet_name=0,header=4, skipfooter=20) #utf-8 -- latin1
oct57 = oct57.dropna()
oct57